Repository LakshaySK106/Algorithms, pull requests merged in 2022-10, with the labels that each got.

#10 Add Searching Algorithms
  CONTRIBUTORS.md
  Searching/Cpp/LinearSearch.cpp
  Searching/Cpp/TernarySearch.cpp
Labels: hacktoberfest-accepted

#11 Added binary search in python
  Searching/Python/binarysearch.py
Labels: hacktoberfest-accepted

#9 cpp codes for recursion - tower of hanoi and nqueens
  recursion/Cpp/nqueens.cpp
  recursion/Cpp/tower_of_hanoi.cpp
Labels: hacktoberfest-accepted

#15 Create insertionsort.cpp
  Searching/Cpp/insertionsort.cpp
Labels: hacktoberfest-accepted

#14 Create bellmanford.cpp
  Searching/Cpp/bellmanford.cpp
Labels: hacktoberfest-accepted

#25 Added DFS for Connected Graph with README.md file
  graph/cpp/README.md
  graph/cpp/dfs.cpp
Labels: hacktoberfest-accepted

#27 Added Floyd Warshall Algorithm
  Greedy-Algo/cpp/README.md
  Greedy-Algo/cpp/floyd-warshall.cpp
Labels: hacktoberfest-accepted

#32 Added Interpolation Search in python
  Searching/Python/Interpolation_search.py
Labels: hacktoberfest-accepted

#22 Created NQueen Problem
  Backtracking/Cpp/NQueen.cpp
Labels: hacktoberfest-accepted

#28 Added trie data structure
  CONTRIBUTORS.md
  trie/Cpp/Implement_Trie.cpp
Labels: hacktoberfest-accepted

#41 Rat in Maze
  Backtracking/JAVA/RatMaze.class
  Backtracking/JAVA/RatMaze.java
Labels: hacktoberfest, hacktoberfest-accepted

#46 Added the program . issue no #39
  Sorting/Cpp/Binary_Insertion_Sort.cpp
Labels: hacktoberfest-accepted

#47 added heap sort algorithm
  Sorting/Cpp/Heap_sort.cpp
Labels: hacktoberfest-accepted

#48 Create bubblesrt.cpp
  Sorting/Cpp/bubblesrt.cpp
Labels: hacktoberfest-accepted

#53 Added Huffman Coding Algorithm
  Greedy-Algo/cpp/Huffman Coding.cpp
Labels: hacktoberfest-accepted

#56 Create Josephus_Problem.cpp
  recursion/Cpp/Josephus_Problem.cpp
Labels: hacktoberfest-accepted

#61 added merge sort in cpp in sorting algorithms
  Sorting/Cpp/Merge_Sort.cpp
Labels: hacktoberfest-accepted

#62 Added solution for prim's minimum spanning tree algorithm
  Greedy-Algo/cpp/Prims_Algorithm.cpp
Labels: hacktoberfest-accepted

#57 Adding iterative merge sort
  Sorting/Python/iterative_merge_sort.py
Labels: hacktoberfest-accepted

#36 Add Binary tree maximum path sum, Add gitignore file
  CONTRIBUTORS.md
  Tree/cpp/binary_tree_maximum_path_sum.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#80 Added LinearSearch.py
  Searching/Python/LinearSearch.py
Labels: hacktoberfest-accepted

#84 Added Recursive code for Taylor Series
  recursion/Cpp/TaylorSeries.cpp
Labels: hacktoberfest-accepted

#91 Added Fast power Recursive method
  recursion/Cpp/Exponent_FastPower.cpp
Labels: hacktoberfest-accepted

#106 Threaded Binary Tree And Convex Hull Algo Implementation
  Data Structures/Cpp/Threaded_binary_tree.cpp
  Polygon Algo/Cpp/Convex_Hull_Algo.cpp
Labels: hacktoberfest-accepted

#141 Added program for LinkedList palindrome
  CONTRIBUTORS.md
  LinkedList/Cpp/linkedListPalindrome.cpp
Labels: hacktoberfest-accepted

#147 Added Kosaraju's algorithm for finding strongly connected components
  graph/cpp/Kosaraju.cpp
Labels: hacktoberfest-accepted

#150 Added Tug Of War Problem
  Backtracking/Cpp/TugOfWar.cpp
Labels: hacktoberfest-accepted
